# Form implementation generated from reading ui file 'app/ui/HabitsPage.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore
from PyQt6 import QtWidgets


class Ui_HabitsPage(object):
    def setupUi(self, HabitsPage):
        HabitsPage.setObjectName("HabitsPage")
        self.verticalLayout = QtWidgets.QVBoxLayout(HabitsPage)
        self.verticalLayout.setObjectName("verticalLayout")
        self.topBarLayout = QtWidgets.QHBoxLayout()
        self.topBarLayout.setObjectName("topBarLayout")
        self.newHabitButton = QtWidgets.QPushButton(parent=HabitsPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.newHabitButton.sizePolicy().hasHeightForWidth())
        self.newHabitButton.setSizePolicy(sizePolicy)
        self.newHabitButton.setObjectName("newHabitButton")
        self.topBarLayout.addWidget(self.newHabitButton)
        spacerItem = QtWidgets.QSpacerItem(
            0, 0, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum
        )
        self.topBarLayout.addItem(spacerItem)
        self.verticalLayout.addLayout(self.topBarLayout)
        self.habitsScrollArea = QtWidgets.QScrollArea(parent=HabitsPage)
        self.habitsScrollArea.setWidgetResizable(True)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.habitsScrollArea.sizePolicy().hasHeightForWidth())
        self.habitsScrollArea.setSizePolicy(sizePolicy)
        self.habitsScrollArea.setObjectName("habitsScrollArea")
        self.habitsContainer = QtWidgets.QWidget()
        self.habitsContainer.setObjectName("habitsContainer")
        self.habitsListLayout = QtWidgets.QVBoxLayout(self.habitsContainer)
        self.habitsListLayout.setAlignment(QtCore.Qt.AlignmentFlag.AlignTop)
        self.habitsListLayout.setObjectName("habitsListLayout")
        self.habitsScrollArea.setWidget(self.habitsContainer)
        self.verticalLayout.addWidget(self.habitsScrollArea)

        self.retranslateUi(HabitsPage)
        QtCore.QMetaObject.connectSlotsByName(HabitsPage)

    def retranslateUi(self, HabitsPage):
        _translate = QtCore.QCoreApplication.translate
        self.newHabitButton.setText(_translate("HabitsPage", "➕ New Habit"))
