# Form implementation generated from reading ui file 'app/ui/HabitDetailDialog.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore
from PyQt6 import QtWidgets


class Ui_HabitDetailDialog(object):
    def setupUi(self, HabitDetailDialog):
        HabitDetailDialog.setObjectName("HabitDetailDialog")
        self.verticalLayout = QtWidgets.QVBoxLayout(HabitDetailDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.titleLayout = QtWidgets.QHBoxLayout()
        self.titleLayout.setObjectName("titleLayout")
        self.titleLabel = QtWidgets.QLabel(parent=HabitDetailDialog)
        self.titleLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeft)
        self.titleLabel.setObjectName("titleLabel")
        self.titleLayout.addWidget(self.titleLabel)
        self.statusLabel = QtWidgets.QLabel(parent=HabitDetailDialog)
        self.statusLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight)
        self.statusLabel.setObjectName("statusLabel")
        self.titleLayout.addWidget(self.statusLabel)
        self.verticalLayout.addLayout(self.titleLayout)
        self.datesLabel = QtWidgets.QLabel(parent=HabitDetailDialog)
        self.datesLabel.setObjectName("datesLabel")
        self.verticalLayout.addWidget(self.datesLabel)
        self.streakLabel = QtWidgets.QLabel(parent=HabitDetailDialog)
        self.streakLabel.setObjectName("streakLabel")
        self.verticalLayout.addWidget(self.streakLabel)
        self.rewardLabel = QtWidgets.QLabel(parent=HabitDetailDialog)
        self.rewardLabel.setObjectName("rewardLabel")
        self.verticalLayout.addWidget(self.rewardLabel)
        self.hardModeLabel = QtWidgets.QLabel(parent=HabitDetailDialog)
        self.hardModeLabel.setObjectName("hardModeLabel")
        self.verticalLayout.addWidget(self.hardModeLabel)
        self.itemsGroup = QtWidgets.QGroupBox(parent=HabitDetailDialog)
        self.itemsGroup.setObjectName("itemsGroup")
        self.itemsLayout = QtWidgets.QVBoxLayout(self.itemsGroup)
        self.itemsLayout.setObjectName("itemsLayout")
        self.verticalLayout.addWidget(self.itemsGroup)
        self.buttonsLayout = QtWidgets.QHBoxLayout()
        self.buttonsLayout.setObjectName("buttonsLayout")
        spacerItem = QtWidgets.QSpacerItem(
            0, 0, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum
        )
        self.buttonsLayout.addItem(spacerItem)
        self.closeButton = QtWidgets.QPushButton(parent=HabitDetailDialog)
        self.closeButton.setObjectName("closeButton")
        self.buttonsLayout.addWidget(self.closeButton)
        self.verticalLayout.addLayout(self.buttonsLayout)

        self.retranslateUi(HabitDetailDialog)
        QtCore.QMetaObject.connectSlotsByName(HabitDetailDialog)

    def retranslateUi(self, HabitDetailDialog):
        _translate = QtCore.QCoreApplication.translate
        HabitDetailDialog.setWindowTitle(_translate("HabitDetailDialog", "Habit Details"))
        self.titleLabel.setText(_translate("HabitDetailDialog", "Title"))
        self.titleLabel.setStyleSheet(_translate("HabitDetailDialog", "font-size:18px; font-weight:bold;"))
        self.statusLabel.setText(_translate("HabitDetailDialog", "Active"))
        self.statusLabel.setStyleSheet(_translate("HabitDetailDialog", "font-weight:bold;"))
        self.datesLabel.setText(_translate("HabitDetailDialog", "Start – End"))
        self.streakLabel.setText(_translate("HabitDetailDialog", "Streak: 0"))
        self.rewardLabel.setText(_translate("HabitDetailDialog", "Reward: …"))
        self.hardModeLabel.setText(_translate("HabitDetailDialog", "Mode: Normal"))
        self.itemsGroup.setTitle(_translate("HabitDetailDialog", "Checklist Items"))
        self.closeButton.setText(_translate("HabitDetailDialog", "Close"))
