# Form implementation generated from reading ui file 'app/ui/HabitCard.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore
from PyQt6 import QtWidgets


class Ui_HabitCard(object):
    def setupUi(self, HabitCard):
        HabitCard.setObjectName("HabitCard")
        HabitCard.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.verticalLayout = QtWidgets.QVBoxLayout(HabitCard)
        self.verticalLayout.setObjectName("verticalLayout")
        self.titleLabel = QtWidgets.QLabel(parent=HabitCard)
        self.titleLabel.setObjectName("titleLabel")
        self.verticalLayout.addWidget(self.titleLabel)
        self.calendarWidget = QtWidgets.QWidget(parent=HabitCard)
        self.calendarWidget.setObjectName("calendarWidget")
        self.calendarLayout = QtWidgets.QVBoxLayout(self.calendarWidget)
        self.calendarLayout.setObjectName("calendarLayout")
        self.verticalLayout.addWidget(self.calendarWidget)

        self.retranslateUi(HabitCard)
        QtCore.QMetaObject.connectSlotsByName(HabitCard)

    def retranslateUi(self, HabitCard):
        _translate = QtCore.QCoreApplication.translate
        self.titleLabel.setText(_translate("HabitCard", "Habit Title"))
        self.titleLabel.setStyleSheet(_translate("HabitCard", "font-size:16px; font-weight:bold;"))
