# Form implementation generated from reading ui file 'app/ui/HabitsPage.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore
from PyQt6 import QtWidgets


class Ui_HabitsPage(object):
    def setupUi(self, HabitsPage):
        HabitsPage.setObjectName("HabitsPage")
        self.verticalLayout = QtWidgets.QVBoxLayout(HabitsPage)
        self.verticalLayout.setObjectName("verticalLayout")

        self.retranslateUi(HabitsPage)
        QtCore.QMetaObject.connectSlotsByName(HabitsPage)

    def retranslateUi(self, HabitsPage):
        pass
