# Form implementation generated from reading ui file 'app/ui/MainWindow.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore
from PyQt6 import QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setMinimumSize(QtCore.QSize(1344, 840))
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.mainLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.mainLayout.setObjectName("mainLayout")
        self.tabBarWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.tabBarWidget.setObjectName("tabBarWidget")
        self.tabBarLayout = QtWidgets.QHBoxLayout(self.tabBarWidget)
        self.tabBarLayout.setObjectName("tabBarLayout")
        self.tabToday = QtWidgets.QPushButton(parent=self.tabBarWidget)
        self.tabToday.setCheckable(True)
        self.tabToday.setChecked(True)
        self.tabToday.setObjectName("tabToday")
        self.tabBarLayout.addWidget(self.tabToday)
        self.tabBoard = QtWidgets.QPushButton(parent=self.tabBarWidget)
        self.tabBoard.setCheckable(True)
        self.tabBoard.setObjectName("tabBoard")
        self.tabBarLayout.addWidget(self.tabBoard)
        self.tabHabits = QtWidgets.QPushButton(parent=self.tabBarWidget)
        self.tabHabits.setCheckable(True)
        self.tabHabits.setObjectName("tabHabits")
        self.tabBarLayout.addWidget(self.tabHabits)
        self.tabSpacer = QtWidgets.QWidget(parent=self.tabBarWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabSpacer.sizePolicy().hasHeightForWidth())
        self.tabSpacer.setSizePolicy(sizePolicy)
        self.tabSpacer.setObjectName("tabSpacer")
        self.tabBarLayout.addWidget(self.tabSpacer)
        self.settingsButton = QtWidgets.QPushButton(parent=self.tabBarWidget)
        self.settingsButton.setObjectName("settingsButton")
        self.tabBarLayout.addWidget(self.settingsButton)
        self.themeToggleButton = QtWidgets.QPushButton(parent=self.tabBarWidget)
        self.themeToggleButton.setObjectName("themeToggleButton")
        self.tabBarLayout.addWidget(self.themeToggleButton)
        self.versionLabel = QtWidgets.QLabel(parent=self.tabBarWidget)
        self.versionLabel.setText("")
        self.versionLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.versionLabel.setObjectName("versionLabel")
        self.tabBarLayout.addWidget(self.versionLabel)
        self.mainLayout.addWidget(self.tabBarWidget)
        self.stackedWidget = QtWidgets.QStackedWidget(parent=self.centralwidget)
        self.stackedWidget.setObjectName("stackedWidget")
        self.today_page = QtWidgets.QWidget()
        self.today_page.setObjectName("today_page")
        self.stackedWidget.addWidget(self.today_page)
        self.board_page = QtWidgets.QWidget()
        self.board_page.setObjectName("board_page")
        self.stackedWidget.addWidget(self.board_page)
        self.habits_page = QtWidgets.QWidget()
        self.habits_page.setObjectName("habits_page")
        self.stackedWidget.addWidget(self.habits_page)
        self.mainLayout.addWidget(self.stackedWidget)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "ToDo Planner 📃"))
        self.tabToday.setText(_translate("MainWindow", "ToDay"))
        self.tabBoard.setText(_translate("MainWindow", "Board"))
        self.tabHabits.setText(_translate("MainWindow", "Habits"))
        self.settingsButton.setToolTip(_translate("MainWindow", "Settings"))
        self.themeToggleButton.setText(_translate("MainWindow", "🌙"))
        self.versionLabel.setStyleSheet(_translate("MainWindow", "color: #888888;"))
