# Form implementation generated from reading ui file 'app/ui/TodayPage.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore
from PyQt6 import QtWidgets


class Ui_TodayPage(object):
    def setupUi(self, TodayPage):
        TodayPage.setObjectName("TodayPage")
        self.verticalLayout = QtWidgets.QVBoxLayout(TodayPage)
        self.verticalLayout.setObjectName("verticalLayout")

        self.retranslateUi(TodayPage)
        QtCore.QMetaObject.connectSlotsByName(TodayPage)

    def retranslateUi(self, TodayPage):
        pass
