# Form implementation generated from reading ui file 'ui/TaskDialog.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore
from PyQt6 import QtWidgets


class Ui_TaskDialog(object):
    def setupUi(self, TaskDialog):
        TaskDialog.setObjectName("TaskDialog")
        self.verticalLayout = QtWidgets.QVBoxLayout(TaskDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.headerLabel = QtWidgets.QLabel(parent=TaskDialog)
        self.headerLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.headerLabel.setObjectName("headerLabel")
        self.verticalLayout.addWidget(self.headerLabel)
        self.titleEdit = QtWidgets.QLineEdit(parent=TaskDialog)
        self.titleEdit.setObjectName("titleEdit")
        self.verticalLayout.addWidget(self.titleEdit)
        self.descriptionEdit = QtWidgets.QTextEdit(parent=TaskDialog)
        self.descriptionEdit.setObjectName("descriptionEdit")
        self.verticalLayout.addWidget(self.descriptionEdit)
        self.priorityCombo = QtWidgets.QComboBox(parent=TaskDialog)
        self.priorityCombo.setObjectName("priorityCombo")
        self.priorityCombo.addItem("")
        self.priorityCombo.addItem("")
        self.priorityCombo.addItem("")
        self.verticalLayout.addWidget(self.priorityCombo)
        self.statusCombo = QtWidgets.QComboBox(parent=TaskDialog)
        self.statusCombo.setObjectName("statusCombo")
        self.statusCombo.addItem("")
        self.statusCombo.addItem("")
        self.statusCombo.addItem("")
        self.statusCombo.addItem("")
        self.verticalLayout.addWidget(self.statusCombo)
        self.dueDateEdit = QtWidgets.QDateEdit(parent=TaskDialog)
        self.dueDateEdit.setCalendarPopup(True)
        self.dueDateEdit.setObjectName("dueDateEdit")
        self.verticalLayout.addWidget(self.dueDateEdit)
        self.createdDateLabel = QtWidgets.QLabel(parent=TaskDialog)
        self.createdDateLabel.setObjectName("createdDateLabel")
        self.verticalLayout.addWidget(self.createdDateLabel)
        self.buttonLayout = QtWidgets.QHBoxLayout()
        self.buttonLayout.setObjectName("buttonLayout")
        self.saveButton = QtWidgets.QPushButton(parent=TaskDialog)
        self.saveButton.setObjectName("saveButton")
        self.buttonLayout.addWidget(self.saveButton)
        self.cancelButton = QtWidgets.QPushButton(parent=TaskDialog)
        self.cancelButton.setObjectName("cancelButton")
        self.buttonLayout.addWidget(self.cancelButton)
        self.verticalLayout.addLayout(self.buttonLayout)

        self.retranslateUi(TaskDialog)
        QtCore.QMetaObject.connectSlotsByName(TaskDialog)

    def retranslateUi(self, TaskDialog):
        _translate = QtCore.QCoreApplication.translate
        TaskDialog.setWindowTitle(_translate("TaskDialog", "Add New Task"))
        self.headerLabel.setText(_translate("TaskDialog", "Add New Task"))
        self.headerLabel.setStyleSheet(_translate("TaskDialog", "font-size: 18px; font-weight: bold;"))
        self.titleEdit.setPlaceholderText(_translate("TaskDialog", "Task Title"))
        self.descriptionEdit.setPlaceholderText(_translate("TaskDialog", "Task Description"))
        self.priorityCombo.setItemText(0, _translate("TaskDialog", "Low"))
        self.priorityCombo.setItemText(1, _translate("TaskDialog", "Medium"))
        self.priorityCombo.setItemText(2, _translate("TaskDialog", "High"))
        self.statusCombo.setItemText(0, _translate("TaskDialog", "Backlog"))
        self.statusCombo.setItemText(1, _translate("TaskDialog", "In Progress"))
        self.statusCombo.setItemText(2, _translate("TaskDialog", "Blocked"))
        self.statusCombo.setItemText(3, _translate("TaskDialog", "Done"))
        self.dueDateEdit.setDisplayFormat(_translate("TaskDialog", "yyyy-MM-dd"))
        self.createdDateLabel.setText(_translate("TaskDialog", "Created: -"))
        self.saveButton.setText(_translate("TaskDialog", "Save"))
        self.cancelButton.setText(_translate("TaskDialog", "Cancel"))
