# Form implementation generated from reading ui file 'app/ui/TodayPage.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore
from PyQt6 import QtWidgets


class Ui_TodayPage(object):
    def setupUi(self, TodayPage):
        TodayPage.setObjectName("TodayPage")
        self.verticalLayout = QtWidgets.QVBoxLayout(TodayPage)
        self.verticalLayout.setSpacing(10)
        self.verticalLayout.setObjectName("verticalLayout")
        self.noHabitsWidget = QtWidgets.QWidget(parent=TodayPage)
        self.noHabitsWidget.setObjectName("noHabitsWidget")
        self.noHabitsLayout = QtWidgets.QVBoxLayout(self.noHabitsWidget)
        self.noHabitsLayout.setAlignment(QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.noHabitsLayout.setSpacing(20)
        self.noHabitsLayout.setObjectName("noHabitsLayout")
        self.noHabitsLabel = QtWidgets.QLabel(parent=self.noHabitsWidget)
        self.noHabitsLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.noHabitsLabel.setObjectName("noHabitsLabel")
        self.noHabitsLayout.addWidget(self.noHabitsLabel)
        self.noHabitsImage = QtWidgets.QLabel(parent=self.noHabitsWidget)
        self.noHabitsImage.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.noHabitsImage.setScaledContents(True)
        self.noHabitsImage.setObjectName("noHabitsImage")
        self.noHabitsLayout.addWidget(self.noHabitsImage)
        self.verticalLayout.addWidget(self.noHabitsWidget, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.habitsScrollArea = QtWidgets.QScrollArea(parent=TodayPage)
        self.habitsScrollArea.setWidgetResizable(True)
        self.habitsScrollArea.setObjectName("habitsScrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.habitsLayout = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.habitsLayout.setContentsMargins(0, 0, 0, 0)
        self.habitsLayout.setSpacing(10)
        self.habitsLayout.setObjectName("habitsLayout")
        self.habitsScrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.habitsScrollArea)

        self.retranslateUi(TodayPage)
        QtCore.QMetaObject.connectSlotsByName(TodayPage)

    def retranslateUi(self, TodayPage):
        _translate = QtCore.QCoreApplication.translate
        self.noHabitsLabel.setText(_translate("TodayPage", "No habits for today or none created yet"))
