# Form implementation generated from reading ui file 'ui/TaskDetailDialog.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_TaskDetailDialog(object):
    def setupUi(self, TaskDetailDialog):
        TaskDetailDialog.setObjectName("TaskDetailDialog")
        self.verticalLayout = QtWidgets.QVBoxLayout(TaskDetailDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.titleLabel = QtWidgets.QLabel(parent=TaskDetailDialog)
        self.titleLabel.setObjectName("titleLabel")
        self.verticalLayout.addWidget(self.titleLabel)
        self.descriptionText = QtWidgets.QTextEdit(parent=TaskDetailDialog)
        self.descriptionText.setReadOnly(True)
        self.descriptionText.setObjectName("descriptionText")
        self.verticalLayout.addWidget(self.descriptionText)
        self.infoLabel = QtWidgets.QLabel(parent=TaskDetailDialog)
        self.infoLabel.setObjectName("infoLabel")
        self.verticalLayout.addWidget(self.infoLabel)
        self.closeButton = QtWidgets.QPushButton(parent=TaskDetailDialog)
        self.closeButton.setObjectName("closeButton")
        self.verticalLayout.addWidget(self.closeButton)

        self.retranslateUi(TaskDetailDialog)
        QtCore.QMetaObject.connectSlotsByName(TaskDetailDialog)

    def retranslateUi(self, TaskDetailDialog):
        _translate = QtCore.QCoreApplication.translate
        TaskDetailDialog.setWindowTitle(_translate("TaskDetailDialog", "Описание задачи"))
        self.titleLabel.setText(_translate("TaskDetailDialog", "Название задачи"))
        self.titleLabel.setStyleSheet(_translate("TaskDetailDialog", "font-size:18px; font-weight:bold;"))
        self.infoLabel.setText(_translate("TaskDetailDialog", "Дедлайн и дата создания"))
        self.infoLabel.setStyleSheet(_translate("TaskDetailDialog", "color:#5e6c84; font-size:12px;"))
        self.closeButton.setText(_translate("TaskDetailDialog", "Закрыть"))
